---

- name: Elasticsearch instance
  hosts: tester-es
  sudo: yes
  roles:
    - elasticsearch
    - kibana
  tags:
    - elasticsearch
  vars:
    - es_major_version: 1.7
    - es_start_service: true
    - es_plugins:
      - plugin: elasticsearch/marvel
        version: latest
    - kibana_version: 4.1.2

- name: Elasticsearch instance
  hosts: tester-es-2
  sudo: yes
  roles:
    - elasticsearch2
    - kibana
  tags:
    - elasticsearch
  vars:
    - kibana_version: 4.3.0
    - kibana_plugins:
      - elastic/sense
